version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get upgrade -y
      - echo $(mksquashfs -version)
      - echo $(node -v)
      - echo $(npm -v)
      - npm install -g mocha
      - curl -L http://enclose.io/nodec/nodec-linux-x64.gz | gunzip > nodec
      - chmod +x nodec
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - npm test
      - ./nodec -o basic-fs ./index.js
  post_build:
    commands:
      - echo Build completed on $(date)
artifacts:
  files:
    - basic-fs