version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get upgrade -y
      - echo $(mksquashfs -version)
      - echo $(node -v)
      - echo $(npm -v)
      - npm install -g mocha
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - zip binary.zip basicfs-$(node ./index.js -v)-$(uname -s)-$(uname -p)
      - echo Build completed on $(date)
artifacts:
  files:
    - binary.zip
